export const TEST_PRODUCT_IMAGES: Record<string, string> = {
  // ── Acrylic Sheets ──────────────────────────────────────────────────────
  "gold-mirror-acrylic-sheet": "/test_product_pictures/acrylic_sheets/gold-acrylic-sheet.png",
  "light-blue-acrylic-sheet-835": "/test_product_pictures/acrylic_sheets/light-blue-acrylic-sheet.png",
  "heavy-orange-acrylic-sheet-206": "/test_product_pictures/acrylic_sheets/heavy-orange-acrylic-sheet.png",
  "green-acrylic-sheet-348": "/test_product_pictures/acrylic_sheets/green-acrylic-sheet.png",
  "pink-acrylic-sheet-158": "/test_product_pictures/acrylic_sheets/pink-acrylic-sheet.png",
  "white-opal-acrylic-sheet-433": "/test_product_pictures/acrylic_sheets/red-acrylic-sheet.png",
  "black-cast-acrylic-sheet-non-light-pass-502": "/test_product_pictures/acrylic_sheets/black-acrylic-sheet.png",
  "orange-acrylic-sheet-266": "/test_product_pictures/acrylic_sheets/orange_acrylic_sheet.png",
  "white-opal-acrylic-sheet-433-2": "/test_product_pictures/acrylic_sheets/white_opal_acrylic_sheet.png",
  "ivory-acrylic-sheet-801": "/test_product_pictures/acrylic_sheets/ivory_acrylic_sheet.png",
  "light-green-acrylic-sheet-635": "/test_product_pictures/acrylic_sheets/light_green_acrylic_sheet.png",
  "magenta-acrylic-sheet-100": "/test_product_pictures/acrylic_sheets/magenta_acrylic_sheet.png",
  "silver-mirror-acrylic-sheet": "/test_product_pictures/acrylic_sheets/silver_mirror_acrylic_sheet.png",
  "gray-cast-acrylic-sheet-500": "/test_product_pictures/acrylic_sheets/gray_acrylic_sheet.png",
  "light-yellow-acrylic-sheet-235": "/test_product_pictures/acrylic_sheets/light_yellow_acrylic_sheet.png",
  "blue-acrylic-sheet-322": "/test_product_pictures/acrylic_sheets/blue_acrylic_sheet.png",
  "yellow-cast-acrylic-sheet-215": "/test_product_pictures/acrylic_sheets/yellow_acrylic_sheet.png",
  "white-opaque-acrylic-sheet-425": "/test_product_pictures/acrylic_sheets/white_opaque_acrylic_sheet.png",
  "white-opaque-milky-acrylic-sheet402": "/test_product_pictures/acrylic_sheets/white_milky_acrylic_sheet.png",
  "transparent-acrylic-sheet-0000": "/test_product_pictures/acrylic_sheets/transparent_acrylic_sheet.png",

  // ── Advertisement Materials ─────────────────────────────────────────────
  "freestanding-digital-signage": "/test_product_pictures/advertisment_materials/freestanding_digital_signage.png",
  "double-sided-illuminating-advertising-stand": "/test_product_pictures/advertisment_materials/double_sided_illuminating_stand.png",
  "double-sided-rotating-illuminated-advertising-stand": "/test_product_pictures/advertisment_materials/double_sided_rotating_illuminated_stand.png",
  "water-base-flag": "/test_product_pictures/advertisment_materials/water_base_flag.png",
  "luxury-promotion-table": "/test_product_pictures/advertisment_materials/luxury_promotion_table.png",
  "aluminum-cross-base-flag": "/test_product_pictures/advertisment_materials/aluminum_cross_base_flag.png",
  "pop-up": "/test_product_pictures/advertisment_materials/pop_up_straight.png",
  "promotion-table": "/test_product_pictures/advertisment_materials/promotion_table.png",
  "pop-up-cruved": "/test_product_pictures/advertisment_materials/pop_up_curved.png",
  "roll-up": "/test_product_pictures/advertisment_materials/roll_up.png",
  "display-stand-x-spider": "/test_product_pictures/advertisment_materials/display_stand_x_spider.png",
  "rectangular-led-frame-stand": "/test_product_pictures/advertisment_materials/rectangular_led_frame_stand.png",
  "floor-standing-led-signage-display": "/test_product_pictures/advertisment_materials/floor_standing_led_signage_display.png",
  "led-menu-stand": "/test_product_pictures/advertisment_materials/led_menu_stand.png",
};
